server:
  port: 8091
  
spring:  application:    name: AGGREGATOR-API
  zipkin:
    base-url: http://localhost:9411/
    
#eureka:#  client:#    register-with-eureka: true
#    fetch-registry: true
#    service-url:#      defaultZore: http://localhost:8761/eureka
#  instance:#    hostname: localhost